export const REQUEST_AUTHENTICATION = 'REQUEST_AUTHENTICATION';
export const REQUEST_TO_GET_ALL_ITEMS = 'REQUEST_TO_GET_ALL_ITEMS';
export const REQUEST_TO_CREATE_ITEM = 'REQUEST_TO_CREATE_ITEM';
export const REQUEST_TO_GET_ITEM = 'REQUEST_TO_GET_ITEM';
export const REQUEST_TO_UPDATE_ITEM = 'REQUEST_TO_UPDATE_ITEM';
export const REQUEST_TO_DELETE_ITEM = 'REQUEST_TO_DELETE_ITEM';
export const REQUEST_TO_SEARCH_ITEMS = 'REQUEST_TO_SEARCH_ITEMS';
