export const LOG_IN_REQUEST = 'LOG_IN_REQUEST';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST';
export const INDEX_REQUEST = 'INDEX_REQUEST';
export const CREATE_REQUEST = 'CREATE_REQUEST';
export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const DELETE_REQUEST = 'DELETE_REQUEST';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
