export const AUTHENTICATION_REQUEST = 'AUTHENTICATION_REQUEST';
export const INDEX_REQUEST = 'INDEX_REQUEST';
export const CREATE_REQUEST = 'CREATE_REQUEST';
export const SHOW_REQUEST = 'SHOW_REQUEST';
export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const DELETE_REQUEST = 'DELETE_REQUEST';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
