export const LOG_IN_REQUEST = 'LOG_IN_REQUEST';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST';
export const INDEX_REQUEST = 'INDEX_REQUEST';
export const CREATE_REQUEST = 'CREATE_REQUEST';
export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const DELETE_REQUEST = 'DELETE_REQUEST';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';

export const SUCCESS_LOG_IN = 'SUCCESS_LOG_IN';
export const SUCCESS_LOG_OUT = 'SUCCESS_LOG_OUT';

export const SET_ITEMS = 'SET_ITEMS';
export const INPUT_TITLE = 'INPUT_TITLE';
export const INPUT_DESCRIPTION = 'INPUT_DESCRIPTION';
export const INPUT_PRICE = 'INPUT_PRICE';
export const INPUT_IMAGE_SRC = 'INPUT_IMAGE_SRC';
export const INPUT_ITEM = 'INPUT_ITEM';
export const CREATE_ITEM = 'CREATE_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const INPUT_KEYWORD = 'INPUT_KEYWORD';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';

export const FAILURE_FETCH = 'FAILURE_FETCH';
