export const INPUT_TITLE = 'INPUT_TITLE';
export const INPUT_DESCRIPTION = 'INPUT_DESCRIPTION';
export const INPUT_PRICE = 'INPUT_PRICE';
export const INPUT_IMAGE_SRC = 'INPUT_IMAGE_SRC';
export const CREATE_ITEM = 'CREATE_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
